name: auth
description: A sample command-line application.
version: 1.2.0
repository: https://github.com/DKMFzF/gRPCChat.git

environment:
  sdk: ^3.3.3

dependencies:
  grpc: ^3.2.4 # Зависимость для gRPC
  protobuf: ^3.1.0 # Зависимость для IDE (protobuf)
  stormberry: ^0.14.0 # Для работы с PostgreSQL
  build_runner: ^2.4.9 # Для работы с моделями ORM
  jaguar_jwt: ^3.0.0 # Для создания JWT (токенов)

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
